name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-maeda-pr-agent-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World by github actions"
