name: hello-lambda-actions

on:
  push:

jobs:
  test:
    runs-on: codebuild-maeda-codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!!"
      - run: date -u
